id = "xbsl"
name = "1C:Element (XBSL)"
version = "0.2.0"
schema_version = 1
authors = ["1C:Element (XBSL) extension contributors"]
description = "1C:Element (XBSL) language support: syntax highlighting"
repository = "https://github.com/acpav/zed-element-extension"
languages = ["languages/xbsl"]

[grammars.xbsl]
repository = "https://github.com/acpav/tree-sitter-xbsl"
rev = "fb99c504a551cb44312a92766d48a2e407ca8389"
