id = "xbsl"
name = "1C:Element (XBSL)"
version = "0.1.0"
schema_version = 1
authors = ["1C:Element (XBSL) extension contributors"]
description = "1C:Element (XBSL) language support: syntax highlighting, indentation, outline"
repository = "https://github.com/acpav/zed-element-extension"
languages = ["languages/xbsl"]

[grammars.xbsl]
repository = "https://github.com/acpav/tree-sitter-xbsl"
rev = "4e39ced7ab9d5432a73b6e04412dc960490ee04a"
